# Generated by Django 5.1 on 2024-08-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_category_blog_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
